M48
; DRILL file {KiCad 9.0.4+dfsg-1} date 2025-08-30T10:27:49-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-30T10:27:49-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X85.54Y-62.95
X90.14Y-62.95
X105.4Y-63.0
X110.0Y-63.0
T2
X66.25Y-54.55
X75.9Y-151.3
X117.6Y-151.3
X127.3Y-54.65
M30
