#!/usr/bin/env python3
# build a static html gallery of board renders for github pages
#
# usage:
#   tools/gallery.py <renders_root> <site_out_dir>
#
# renders_root holds one subdir per board, each containing that board's render
# files (<base>_3d_top.png, _3d_bottom.png, _pcb.pdf, _schematic.pdf). copies
# them into the site dir and writes an index.html card grid

import html
import os
import shutil
import sys


def find_boards(root):
    # each immediate subdir with files is one board
    boards = []
    for name in sorted(os.listdir(root)):
        d = os.path.join(root, name)
        if os.path.isdir(d) and os.listdir(d):
            boards.append((name, d))
    return boards


def pick(files, suffix):
    # first file ending with suffix, else none
    for f in sorted(files):
        if f.endswith(suffix):
            return f
    return None


def card(name, rel, files):
    top = pick(files, "_3d_top.png")
    bottom = pick(files, "_3d_bottom.png")
    pcb = pick(files, "_pcb.pdf")
    sch = pick(files, "_schematic.pdf")

    imgs = ""
    for label, f in (("top", top), ("bottom", bottom)):
        if f:
            src = html.escape(f"{rel}/{f}")
            imgs += (f'<figure><img loading="lazy" src="{src}" '
                     f'alt="{html.escape(name)} {label}">'
                     f'<figcaption>{label}</figcaption></figure>')

    links = ""
    for label, f in (("schematic pdf", sch), ("pcb layers pdf", pcb)):
        if f:
            href = html.escape(f"{rel}/{f}")
            links += f'<a href="{href}">{label}</a>'

    return (f'<section class="card"><h2>{html.escape(name)}</h2>'
            f'<div class="imgs">{imgs}</div>'
            f'<div class="links">{links}</div></section>')


def build(root, out):
    boards = find_boards(root)
    os.makedirs(out, exist_ok=True)

    cards = []
    for name, renders in boards:
        rel = name
        dst = os.path.join(out, rel)
        os.makedirs(dst, exist_ok=True)
        files = []
        for f in os.listdir(renders):
            shutil.copy2(os.path.join(renders, f), os.path.join(dst, f))
            files.append(f)
        cards.append(card(name, rel, files))

    body = "\n".join(cards) if cards else "<p>no renders found</p>"
    page = TEMPLATE.replace("{{cards}}", body).replace("{{count}}", str(len(boards)))
    with open(os.path.join(out, "index.html"), "w", encoding="utf-8") as fh:
        fh.write(page)
    print(f"gallery: {len(boards)} board(s) -> {out}/index.html")


TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>signalmesh CAD renders</title>
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 2rem 1.25rem 4rem;
    font: 16px/1.5 system-ui, sans-serif;
    background: #0d1117; color: #e6edf3;
  }
  @media (prefers-color-scheme: light) {
    body { background: #f6f8fa; color: #1f2328; }
  }
  header { max-width: 1200px; margin: 0 auto 2rem; }
  h1 { margin: 0 0 .25rem; font-size: 1.5rem; }
  .sub { opacity: .65; font-size: .9rem; }
  .grid {
    max-width: 1200px; margin: 0 auto;
    display: grid; gap: 1.5rem;
    grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
  }
  .card {
    border: 1px solid #30363d; border-radius: 12px;
    padding: 1rem; background: #161b22;
  }
  @media (prefers-color-scheme: light) {
    .card { border-color: #d0d7de; background: #fff; }
  }
  .card h2 { margin: 0 0 .75rem; font-size: 1.05rem; }
  .imgs { display: grid; grid-template-columns: 1fr 1fr; gap: .5rem; }
  figure { margin: 0; }
  figure img {
    width: 100%; height: auto; border-radius: 8px;
    background: repeating-conic-gradient(#8883 0% 25%, transparent 0% 50%) 50% / 16px 16px;
  }
  figcaption { font-size: .75rem; opacity: .6; text-align: center; margin-top: .25rem; }
  .links { margin-top: .75rem; display: flex; gap: .75rem; flex-wrap: wrap; }
  .links a { font-size: .85rem; color: #4493f8; text-decoration: none; }
  .links a:hover { text-decoration: underline; }
</style>
</head>
<body>
<header>
  <h1>signalmesh CAD renders</h1>
  <div class="sub">{{count}} board(s) - auto-generated by ci</div>
</header>
<main class="grid">
{{cards}}
</main>
</body>
</html>
"""


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("usage: tools/gallery.py <renders_root> <site_out_dir>", file=sys.stderr)
        sys.exit(2)
    build(sys.argv[1], sys.argv[2])
